project:
  type: website

website:
  title: "VT1_Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

